# the name of Camel
camel:
  springboot.name: hl7-to-kafka
  component:
    kafka:
      brokers: ${BOOTSTRAP_SERVERS:localhost:9092}
      ssl-endpoint-algorithm: ${SECURITY_PROTOCOL:PLAINTEXT}
      ssl-truststore-password: ${SSL_TRUST_STORE_PASSWORD}
      ssl-truststore-location: /opt/hl7-to-kafka/ssl/truststore.jks
      ssl-keystore-password: ${SSL_KEY_STORE_PASSWORD}
      ssl-keystore-location: /opt/hl7-to-kafka/ssl/keystore.jks

endpoint:
  kafka.topic: hl7-topic
  hl7:
    port: 2575
    encoding: iso-8859-1

management.endpoints.web.exposure.include: info,health,camelroutes
management.endpoint:
  health.enabled: true
  camelroutes:
    enabled: true
    read-only: true
# to configure logging levels
#logging.level.org.springframework = INFO
#logging.level.org.apache.camel.spring.boot = INFO
#logging.level.org.apache.camel.impl = DEBUG
#logging.level.sample.camel = DEBUG
