camel:
  component:
    kafka:
      brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      security-protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      ssl-truststore-password: ${KAFKA_SSL_TRUST_STORE_PASSWORD}
      ssl-keystore-password: ${KAFKA_SSL_KEY_STORE_PASSWORD}
      ssl-truststore-location: ${KAFKA_SSL_TRUST_STORE_LOCATION_INTERNAL:/opt/hl7-to-kafka/ssl/truststore.jks}
      ssl-keystore-location: ${KAFKA_SSL_KEY_STORE_LOCATION_INTERNAL:/opt/hl7-to-kafka/ssl/keystore.jks}
  main:
    name: hl7-to-kafka

endpoint:
  kafka.topic: ${KAFKA_TOPIC:hl7-topic}
  hl7:
    port: 2575
    encoding: iso-8859-1

management.endpoints.web.exposure.include: info,health,camelroutes
management.endpoint:
  health.enabled: true
  camelroutes:
    enabled: true
    read-only: true
# to configure logging levels
#logging.level.org.springframework = INFO
#logging.level.org.apache.camel.spring.boot = INFO
#logging.level.org.apache.camel.impl = DEBUG
#logging.level.sample.camel = DEBUG
