---
name: build

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.5.0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
